/* Products Options for Honda */

INSERT INTO `products_options` VALUES(1, 1, 'Main Color', 100, 0, 32, '', 32, 0, 0, 0);
INSERT INTO `products_options` VALUES(17, 1, 'Name Color', 503, 0, 32, '', 32, 0, 0, 0);
INSERT INTO `products_options` VALUES(16, 1, 'Accent Color 1', 120, 0, 32, '', 32, 0, 0, 0);
INSERT INTO `products_options` VALUES(18, 1, 'Number Font <a href=javascript:imagePopUp(''http://www.magiksc.com/images/fontpic2.gif'')> [Click To View]</a>', 502, 0, 32, '', 32, 0, 0, 0);
INSERT INTO `products_options` VALUES(23, 1, 'Year', 10, 0, 32, NULL, 32, 0, 0, 0);
INSERT INTO `products_options` VALUES(24, 1, 'Model', 11, 0, 32, NULL, 32, 0, 0, 0);
INSERT INTO `products_options` VALUES(26, 1, 'Race Number', 498, 1, 32, '', 32, 0, 0, 1);
INSERT INTO `products_options` VALUES(27, 1, 'Number Color', 501, 0, 32, '', 32, 0, 0, 0);
INSERT INTO `products_options` VALUES(30, 1, 'Name on Side Panel', 550, 0, 32, '', 32, 0, 0, 0);
INSERT INTO `products_options` VALUES(31, 1, 'Rider Name', 502, 1, 32, '', 32, 0, 0, 0);
INSERT INTO `products_options` VALUES(32, 1, 'Accent Color 2', 121, 0, 32, NULL, 32, 0, 0, 0);
INSERT INTO `products_options` VALUES(33, 1, 'Name Font <a href=javascript:imagePopUp(''../../../../../images/fontpic2.gif'')> [Click To View]</a>', 503, 0, 32, '', 32, 0, 0, 0);
INSERT INTO `products_options` VALUES(34, 1, 'Number Plate Background Color', 123, 0, 32, '', 32, 0, 0, 0);
INSERT INTO `products_options` VALUES(35, 1, 'Additional Information', 1105, 1, 300, '', 300, 0, 0, 4);
INSERT INTO `products_options` VALUES(36, 1, 'Do you want to include UFO replacement plastics?', 1095, 0, 32, '', 32, 0, 0, 0);
INSERT INTO `products_options` VALUES(37, 1, 'Plastics Color [If selected Above]', 1096, 0, 32, '', 32, 0, 0, 0);
INSERT INTO `products_options` VALUES(38, 1, 'Please mount my order', 1097, 0, 32, '', 32, 0, 0, 0);
INSERT INTO `products_options` VALUES(54, 1, 'Shroud Logo 1 (main)', 855, 1, 32, '', 32, 0, 0, 1);
INSERT INTO `products_options` VALUES(40, 1, 'Front Fender Logo 1', 899, 1, 32, '', 32, 0, 0, 0);
INSERT INTO `products_options` VALUES(55, 1, 'Shroud Logo 2', 856, 1, 32, NULL, 32, 0, 0, 1);
INSERT INTO `products_options` VALUES(41, 1, 'Rear Fender Logo 1 (sides)', 920, 1, 32, '', 32, 0, 0, 1);
INSERT INTO `products_options` VALUES(43, 1, 'Rear Fender Logo 2', 922, 1, 32, '', 32, 0, 0, 1);
INSERT INTO `products_options` VALUES(44, 1, 'Rear Fender Logo 3', 924, 1, 32, '', 32, 0, 0, 1);
INSERT INTO `products_options` VALUES(45, 1, 'Rear Fender Logo 4', 926, 1, 32, '', 32, 0, 0, 1);
INSERT INTO `products_options` VALUES(46, 1, 'Rear Fender Logo 5', 928, 1, 32, '', 32, 0, 0, 1);
INSERT INTO `products_options` VALUES(56, 1, 'Shroud Logo 3', 857, 1, 32, NULL, 32, 0, 0, 1);
INSERT INTO `products_options` VALUES(47, 1, 'Rear Fender Logo 6', 930, 1, 32, '', 32, 0, 0, 0);
INSERT INTO `products_options` VALUES(48, 1, 'Rear Fender Logo 7', 932, 1, 32, '', 32, 0, 0, 1);
INSERT INTO `products_options` VALUES(49, 1, 'Rear Fender Logo 8', 934, 1, 32, '', 32, 0, 0, 1);
INSERT INTO `products_options` VALUES(60, 1, 'Swing Arm Logo 1', 850, 1, 32, NULL, 32, 0, 0, 1);
INSERT INTO `products_options` VALUES(51, 1, 'Custom Logo 1', 1090, 4, 32, '', 32, 0, 0, 0);
INSERT INTO `products_options` VALUES(57, 1, 'Air Box Logo 1', 840, 1, 32, '', 32, 0, 0, 1);
INSERT INTO `products_options` VALUES(58, 1, 'Air Box Logo 2', 841, 1, 32, NULL, 32, 0, 0, 1);
INSERT INTO `products_options` VALUES(59, 1, 'Air Box Logo 3', 843, 1, 32, NULL, 32, 0, 0, 1);
INSERT INTO `products_options` VALUES(52, 1, 'Custom Logo 2', 1091, 4, 32, '', 32, 0, 0, 0);
INSERT INTO `products_options` VALUES(53, 1, 'Custom Logo 3', 1092, 4, 32, '', 32, 0, 0, 0);
INSERT INTO `products_options` VALUES(61, 1, 'Swing Arm Logo 2', 851, 1, 32, NULL, 32, 0, 0, 1);
INSERT INTO `products_options` VALUES(62, 1, 'Swing Arm Logo 3', 852, 1, 32, NULL, 32, 0, 0, 1);
INSERT INTO `products_options` VALUES(63, 1, 'Fork Guard Logo 1', 880, 1, 32, NULL, 32, 0, 0, 1);
INSERT INTO `products_options` VALUES(64, 1, 'Fork Guard Logo 2', 881, 1, 32, NULL, 32, 0, 0, 1);
INSERT INTO `products_options` VALUES(65, 1, 'Fork Guard Logo 3', 882, 1, 32, NULL, 32, 0, 0, 1);
INSERT INTO `products_options` VALUES(66, 1, 'Fork Guard Logo 4', 883, 1, 32, NULL, 32, 0, 0, 1);
INSERT INTO `products_options` VALUES(67, 1, 'Front Fender Logo 2', 900, 1, 32, NULL, 32, 0, 0, 1);
INSERT INTO `products_options` VALUES(68, 1, 'Front Fender Logo 3', 901, 1, 32, '', 32, 0, 0, 1);
INSERT INTO `products_options` VALUES(86, 1, 'Rush Order', 1102, 0, 32, '', 32, 0, 0, 0);

/* Prod Option Types */

INSERT INTO `products_options_types` VALUES('Dropdown');
INSERT INTO `products_options_types` VALUES('Text');
INSERT INTO `products_options_types` VALUES('Radio');
INSERT INTO `products_options_types` VALUES('Checkbox');
INSERT INTO `products_options_types` VALUES('File');
INSERT INTO `products_options_types` VALUES('Read Only');
INSERT INTO `products_options_types` VALUES('Grid');

/* Prod Option Values */

INSERT INTO `products_options_values` VALUES(2, 1, 'Yellow', 160);
INSERT INTO `products_options_values` VALUES(6, 1, 'Blue', 150);
INSERT INTO `products_options_values` VALUES(11, 1, 'Black', 100);
INSERT INTO `products_options_values` VALUES(12, 1, 'Orange', 170);
INSERT INTO `products_options_values` VALUES(13, 1, 'KX Green', 155);
INSERT INTO `products_options_values` VALUES(14, 1, 'Chrome', 190);
INSERT INTO `products_options_values` VALUES(15, 1, 'Gold Chrome', 195);
INSERT INTO `products_options_values` VALUES(16, 1, 'Metallic Grey', 130);
INSERT INTO `products_options_values` VALUES(17, 1, 'Dark Grey', 120);
INSERT INTO `products_options_values` VALUES(18, 1, 'White', 110);
INSERT INTO `products_options_values` VALUES(19, 1, 'Hot Pink', 185);
INSERT INTO `products_options_values` VALUES(20, 1, 'Neon Pink', 180);
INSERT INTO `products_options_values` VALUES(35, 1, 'Black', 100);
INSERT INTO `products_options_values` VALUES(112, 1, 'Red', 0);
INSERT INTO `products_options_values` VALUES(97, 1, 'Tech (Italic)', 10);
INSERT INTO `products_options_values` VALUES(96, 1, 'Tech', 10);
INSERT INTO `products_options_values` VALUES(62, 1, 'Red', 140);
INSERT INTO `products_options_values` VALUES(63, 1, 'Yellow', 160);
INSERT INTO `products_options_values` VALUES(64, 1, 'Blue', 150);
INSERT INTO `products_options_values` VALUES(88, 1, 'Pro', 1);
INSERT INTO `products_options_values` VALUES(66, 1, 'Orange', 170);
INSERT INTO `products_options_values` VALUES(67, 1, 'KX Green', 155);
INSERT INTO `products_options_values` VALUES(68, 1, 'Chrome', 190);
INSERT INTO `products_options_values` VALUES(69, 1, 'Gold Chrome', 195);
INSERT INTO `products_options_values` VALUES(70, 1, 'Metallic Silver', 130);
INSERT INTO `products_options_values` VALUES(71, 1, 'Dark Grey', 120);
INSERT INTO `products_options_values` VALUES(72, 1, 'White', 110);
INSERT INTO `products_options_values` VALUES(73, 1, 'Hot Pink', 185);
INSERT INTO `products_options_values` VALUES(74, 1, 'Neon Pink', 180);
INSERT INTO `products_options_values` VALUES(95, 1, 'Ready (Italic)', 10);
INSERT INTO `products_options_values` VALUES(94, 1, 'Ready', 10);
INSERT INTO `products_options_values` VALUES(93, 1, 'Coast (Italic)', 10);
INSERT INTO `products_options_values` VALUES(92, 1, 'Coast', 10);
INSERT INTO `products_options_values` VALUES(91, 1, 'Factory (Italic)', 10);
INSERT INTO `products_options_values` VALUES(90, 1, 'Factory', 10);
INSERT INTO `products_options_values` VALUES(89, 1, 'Pro (Italic)', 2);
INSERT INTO `products_options_values` VALUES(414, 1, 'CRF 250X', 20);
INSERT INTO `products_options_values` VALUES(85, 1, 'White', 110);
INSERT INTO `products_options_values` VALUES(78, 1, 'Black', 100);
INSERT INTO `products_options_values` VALUES(163, 1, 'CRF 50F', 20);
INSERT INTO `products_options_values` VALUES(164, 1, '2010', 20);
INSERT INTO `products_options_values` VALUES(165, 1, '2009', 21);
INSERT INTO `products_options_values` VALUES(166, 1, '2008', 22);
INSERT INTO `products_options_values` VALUES(167, 1, '2007', 23);
INSERT INTO `products_options_values` VALUES(168, 1, '2006', 24);
INSERT INTO `products_options_values` VALUES(169, 1, '2005', 25);
INSERT INTO `products_options_values` VALUES(170, 1, '2004', 26);
INSERT INTO `products_options_values` VALUES(171, 1, '2003', 27);
INSERT INTO `products_options_values` VALUES(172, 1, '2002', 28);
INSERT INTO `products_options_values` VALUES(173, 1, '2001', 29);
INSERT INTO `products_options_values` VALUES(174, 1, '2000', 30);
INSERT INTO `products_options_values` VALUES(175, 1, '1999', 31);
INSERT INTO `products_options_values` VALUES(176, 1, 'CR 85', 20);
INSERT INTO `products_options_values` VALUES(177, 1, 'CRF 150R', 20);
INSERT INTO `products_options_values` VALUES(178, 1, 'CR 125', 20);
INSERT INTO `products_options_values` VALUES(179, 1, 'CR 250', 20);
INSERT INTO `products_options_values` VALUES(180, 1, 'CRF 250', 20);
INSERT INTO `products_options_values` VALUES(181, 1, 'CRF 450', 20);
INSERT INTO `products_options_values` VALUES(186, 1, 'Black', 0);
INSERT INTO `products_options_values` VALUES(189, 1, 'White', 0);
INSERT INTO `products_options_values` VALUES(197, 1, 'Add Name to Side Panel', 0);
INSERT INTO `products_options_values` VALUES(198, 1, 'No Thanks', 0);
INSERT INTO `products_options_values` VALUES(199, 1, 'Black', 100);
INSERT INTO `products_options_values` VALUES(200, 1, 'Red', 140);
INSERT INTO `products_options_values` VALUES(201, 1, 'Yellow', 160);
INSERT INTO `products_options_values` VALUES(202, 1, 'Blue', 150);
INSERT INTO `products_options_values` VALUES(203, 1, 'Orange', 170);
INSERT INTO `products_options_values` VALUES(205, 1, 'Chrome', 190);
INSERT INTO `products_options_values` VALUES(206, 1, 'Gold Chrome', 195);
INSERT INTO `products_options_values` VALUES(207, 1, 'Metallic Silver', 130);
INSERT INTO `products_options_values` VALUES(208, 1, 'Dark Grey', 120);
INSERT INTO `products_options_values` VALUES(209, 1, 'White', 110);
INSERT INTO `products_options_values` VALUES(210, 1, 'Hot Pink', 185);
INSERT INTO `products_options_values` VALUES(211, 1, 'Neon Pink', 180);
INSERT INTO `products_options_values` VALUES(212, 1, 'Pro', 1);
INSERT INTO `products_options_values` VALUES(213, 1, 'Pro (Italic)', 2);
INSERT INTO `products_options_values` VALUES(214, 1, 'Factory', 10);
INSERT INTO `products_options_values` VALUES(215, 1, 'Factory (Italic)', 10);
INSERT INTO `products_options_values` VALUES(216, 1, 'Coast', 10);
INSERT INTO `products_options_values` VALUES(217, 1, 'Coast (Italic)', 10);
INSERT INTO `products_options_values` VALUES(218, 1, 'Ready', 10);
INSERT INTO `products_options_values` VALUES(219, 1, 'Ready (Italic)', 10);
INSERT INTO `products_options_values` VALUES(220, 1, 'Tech', 10);
INSERT INTO `products_options_values` VALUES(221, 1, 'Tech (Italic)', 10);
INSERT INTO `products_options_values` VALUES(222, 1, 'White', 0);
INSERT INTO `products_options_values` VALUES(223, 1, 'Black', 0);
INSERT INTO `products_options_values` VALUES(226, 1, 'No', 0);
INSERT INTO `products_options_values` VALUES(225, 1, 'Red', 1);
INSERT INTO `products_options_values` VALUES(227, 1, '50 cc', 2);
INSERT INTO `products_options_values` VALUES(236, 1, 'No', 1);
INSERT INTO `products_options_values` VALUES(229, 1, '125 - 450 cc', 5);
INSERT INTO `products_options_values` VALUES(234, 1, 'Black', 2);
INSERT INTO `products_options_values` VALUES(231, 1, '85 cc', 4);
INSERT INTO `products_options_values` VALUES(233, 1, 'White', 1);
INSERT INTO `products_options_values` VALUES(235, 1, 'OEM Stock', 0);
INSERT INTO `products_options_values` VALUES(237, 1, 'Yes', 2);
INSERT INTO `products_options_values` VALUES(272, 1, 'Please Select', 1);
INSERT INTO `products_options_values` VALUES(273, 1, 'Please Select', 1);
INSERT INTO `products_options_values` VALUES(275, 1, 'Add', 10);
INSERT INTO `products_options_values` VALUES(276, 1, 'Add (Italic)', 10);
INSERT INTO `products_options_values` VALUES(277, 1, 'Add', 10);
INSERT INTO `products_options_values` VALUES(278, 1, 'Add (Italic)', 10);
INSERT INTO `products_options_values` VALUES(578, 1, 'Gray', 0);
INSERT INTO `products_options_values` VALUES(298, 1, 'Cyan Blue', 152);
INSERT INTO `products_options_values` VALUES(299, 1, 'Cyan Blue', 152);
INSERT INTO `products_options_values` VALUES(302, 1, 'Cyan Blue', 152);
INSERT INTO `products_options_values` VALUES(304, 1, 'Match to Accent', 152);
INSERT INTO `products_options_values` VALUES(314, 1, 'Yellow', 1);
INSERT INTO `products_options_values` VALUES(316, 1, 'Cyan Blue', 1);
INSERT INTO `products_options_values` VALUES(339, 1, '2011', 19);
INSERT INTO `products_options_values` VALUES(340, 1, '2012', 18);
INSERT INTO `products_options_values` VALUES(355, 1, 'True Green', 215);
INSERT INTO `products_options_values` VALUES(347, 1, 'Purple', 205);
INSERT INTO `products_options_values` VALUES(348, 1, 'Purple', 205);
INSERT INTO `products_options_values` VALUES(349, 1, 'Purple', 205);
INSERT INTO `products_options_values` VALUES(415, 1, 'CRF 450X', 20);
INSERT INTO `products_options_values` VALUES(356, 1, 'True Green', 215);
INSERT INTO `products_options_values` VALUES(357, 1, 'True Green', 215);
INSERT INTO `products_options_values` VALUES(361, 1, 'Metallic Gold', 131);
INSERT INTO `products_options_values` VALUES(362, 1, 'Metallic Gold', 132);
INSERT INTO `products_options_values` VALUES(363, 1, 'Metallic Gold', 132);
INSERT INTO `products_options_values` VALUES(367, 1, 'Ruby Red', 225);
INSERT INTO `products_options_values` VALUES(368, 1, 'Ruby Red', 225);
INSERT INTO `products_options_values` VALUES(369, 1, 'Ruby Red', 225);
INSERT INTO `products_options_values` VALUES(373, 1, 'Teal/Aqua', 230);
INSERT INTO `products_options_values` VALUES(374, 1, 'Teal/Aqua', 230);
INSERT INTO `products_options_values` VALUES(375, 1, 'Teal/Aqua', 230);
INSERT INTO `products_options_values` VALUES(379, 1, 'Blue', 200);
INSERT INTO `products_options_values` VALUES(382, 1, 'XR 650 R', 20);
INSERT INTO `products_options_values` VALUES(391, 1, 'Clear Background', 0);
INSERT INTO `products_options_values` VALUES(446, 1, '2013', 17);
INSERT INTO `products_options_values` VALUES(435, 1, 'KTM 450 SFX 07-09', 50);
INSERT INTO `products_options_values` VALUES(436, 1, 'KTM 450 SXF 05-06 [OEM Only]', 45);
INSERT INTO `products_options_values` VALUES(437, 1, 'KTM 250 SX 07-08 [OEM Only]', 40);
INSERT INTO `products_options_values` VALUES(464, 1, 'KX Green', 151);
INSERT INTO `products_options_values` VALUES(583, 1, 'Gray', 0);
INSERT INTO `products_options_values` VALUES(466, 1, 'KX Green', 151);
INSERT INTO `products_options_values` VALUES(500, 1, 'Red Chrome', 192);
INSERT INTO `products_options_values` VALUES(501, 1, 'Blue Chrome', 193);
INSERT INTO `products_options_values` VALUES(502, 1, 'Red Chrome', 192);
INSERT INTO `products_options_values` VALUES(503, 1, 'Blue Chrome', 193);
INSERT INTO `products_options_values` VALUES(504, 1, 'Red Chrome', 192);
INSERT INTO `products_options_values` VALUES(517, 1, 'Pink', 178);
INSERT INTO `products_options_values` VALUES(510, 1, 'Blue Chrome', 193);
INSERT INTO `products_options_values` VALUES(518, 1, 'Pink', 178);
INSERT INTO `products_options_values` VALUES(516, 1, 'Pink', 178);
INSERT INTO `products_options_values` VALUES(533, 1, '2014', 16);
INSERT INTO `products_options_values` VALUES(522, 1, 'Neon Green', 217);
INSERT INTO `products_options_values` VALUES(523, 1, 'Neon Green', 217);
INSERT INTO `products_options_values` VALUES(524, 1, 'Neon Green', 217);
INSERT INTO `products_options_values` VALUES(528, 1, 'No', 1);
INSERT INTO `products_options_values` VALUES(530, 1, 'Yes (Proof in 2 busness days for graphic kits only)', 3);
INSERT INTO `products_options_values` VALUES(563, 1, '2015', 15);
INSERT INTO `products_options_values` VALUES(582, 1, 'Gray', 0);
INSERT INTO `products_options_values` VALUES(580, 1, 'Gray', 0);
INSERT INTO `products_options_values` VALUES(579, 1, 'Gray', 0);
INSERT INTO `products_options_values` VALUES(572, 1, 'Flo Yellow', 196);
INSERT INTO `products_options_values` VALUES(573, 1, 'Flo Yellow', 196);
INSERT INTO `products_options_values` VALUES(574, 1, 'Flo Yellow', 196);
INSERT INTO `products_options_values` VALUES(584, 1, 'Camo', 1400);
INSERT INTO `products_options_values` VALUES(585, 1, 'Camo', 1000);
INSERT INTO `products_options_values` VALUES(586, 1, 'Camo', 1200);
INSERT INTO `products_options_values` VALUES(588, 1, 'Camo', 0);
INSERT INTO `products_options_values` VALUES(589, 1, 'Camo', 0);
INSERT INTO `products_options_values` VALUES(593, 1, 'Gun Metal Grey', 131);
INSERT INTO `products_options_values` VALUES(594, 1, 'Gun Metal Metallic', 131);
INSERT INTO `products_options_values` VALUES(595, 1, 'Gun Metal Metallic', 131);
INSERT INTO `products_options_values` VALUES(597, 1, 'Gun Metal Grey', 131);
INSERT INTO `products_options_values` VALUES(598, 1, 'Gun Metal Grey', 131);
INSERT INTO `products_options_values` VALUES(648, 1, '', 0);
INSERT INTO `products_options_values` VALUES(649, 1, '', 0);
INSERT INTO `products_options_values` VALUES(650, 1, '', 0);
INSERT INTO `products_options_values` VALUES(652, 1, '', 0);
INSERT INTO `products_options_values` VALUES(653, 1, '', 0);
INSERT INTO `products_options_values` VALUES(655, 1, '2017', 13);
INSERT INTO `products_options_values` VALUES(656, 1, '2018', 12);
INSERT INTO `products_options_values` VALUES(657, 1, '2019', 11);

/* Options to Values and products to options */

INSERT INTO `products_options_values_to_products_options` VALUES(1, 1, 1);
INSERT INTO `products_options_values_to_products_options` VALUES(2, 1, 2);
INSERT INTO `products_options_values_to_products_options` VALUES(6, 1, 6);
INSERT INTO `products_options_values_to_products_options` VALUES(474, 24, 380);
INSERT INTO `products_options_values_to_products_options` VALUES(476, 24, 382);
INSERT INTO `products_options_values_to_products_options` VALUES(475, 24, 381);
INSERT INTO `products_options_values_to_products_options` VALUES(22, 1, 11);
INSERT INTO `products_options_values_to_products_options` VALUES(23, 1, 12);
INSERT INTO `products_options_values_to_products_options` VALUES(25, 1, 14);
INSERT INTO `products_options_values_to_products_options` VALUES(26, 1, 15);
INSERT INTO `products_options_values_to_products_options` VALUES(27, 1, 16);
INSERT INTO `products_options_values_to_products_options` VALUES(28, 1, 17);
INSERT INTO `products_options_values_to_products_options` VALUES(29, 1, 18);
INSERT INTO `products_options_values_to_products_options` VALUES(30, 1, 19);
INSERT INTO `products_options_values_to_products_options` VALUES(31, 1, 20);
INSERT INTO `products_options_values_to_products_options` VALUES(46, 16, 35);
INSERT INTO `products_options_values_to_products_options` VALUES(766, 24, 660);
INSERT INTO `products_options_values_to_products_options` VALUES(765, 24, 659);
INSERT INTO `products_options_values_to_products_options` VALUES(764, 24, 658);
INSERT INTO `products_options_values_to_products_options` VALUES(767, 24, 661);
INSERT INTO `products_options_values_to_products_options` VALUES(150, 1, 112);
INSERT INTO `products_options_values_to_products_options` VALUES(73, 16, 62);
INSERT INTO `products_options_values_to_products_options` VALUES(74, 16, 63);
INSERT INTO `products_options_values_to_products_options` VALUES(75, 16, 64);
INSERT INTO `products_options_values_to_products_options` VALUES(126, 18, 88);
INSERT INTO `products_options_values_to_products_options` VALUES(77, 16, 66);
INSERT INTO `products_options_values_to_products_options` VALUES(78, 16, 67);
INSERT INTO `products_options_values_to_products_options` VALUES(79, 16, 68);
INSERT INTO `products_options_values_to_products_options` VALUES(80, 16, 69);
INSERT INTO `products_options_values_to_products_options` VALUES(81, 16, 70);
INSERT INTO `products_options_values_to_products_options` VALUES(82, 16, 71);
INSERT INTO `products_options_values_to_products_options` VALUES(83, 16, 72);
INSERT INTO `products_options_values_to_products_options` VALUES(84, 16, 73);
INSERT INTO `products_options_values_to_products_options` VALUES(85, 16, 74);
INSERT INTO `products_options_values_to_products_options` VALUES(135, 18, 97);
INSERT INTO `products_options_values_to_products_options` VALUES(134, 18, 96);
INSERT INTO `products_options_values_to_products_options` VALUES(133, 18, 95);
INSERT INTO `products_options_values_to_products_options` VALUES(132, 18, 94);
INSERT INTO `products_options_values_to_products_options` VALUES(131, 18, 93);
INSERT INTO `products_options_values_to_products_options` VALUES(130, 18, 92);
INSERT INTO `products_options_values_to_products_options` VALUES(129, 18, 91);
INSERT INTO `products_options_values_to_products_options` VALUES(128, 18, 90);
INSERT INTO `products_options_values_to_products_options` VALUES(127, 18, 89);
INSERT INTO `products_options_values_to_products_options` VALUES(123, 17, 85);
INSERT INTO `products_options_values_to_products_options` VALUES(718, 24, 614);
INSERT INTO `products_options_values_to_products_options` VALUES(116, 17, 78);
INSERT INTO `products_options_values_to_products_options` VALUES(203, 24, 163);
INSERT INTO `products_options_values_to_products_options` VALUES(204, 23, 164);
INSERT INTO `products_options_values_to_products_options` VALUES(205, 23, 165);
INSERT INTO `products_options_values_to_products_options` VALUES(206, 23, 166);
INSERT INTO `products_options_values_to_products_options` VALUES(207, 23, 167);
INSERT INTO `products_options_values_to_products_options` VALUES(208, 23, 168);
INSERT INTO `products_options_values_to_products_options` VALUES(209, 23, 169);
INSERT INTO `products_options_values_to_products_options` VALUES(210, 23, 170);
INSERT INTO `products_options_values_to_products_options` VALUES(211, 23, 171);
INSERT INTO `products_options_values_to_products_options` VALUES(212, 23, 172);
INSERT INTO `products_options_values_to_products_options` VALUES(213, 23, 173);
INSERT INTO `products_options_values_to_products_options` VALUES(214, 23, 174);
INSERT INTO `products_options_values_to_products_options` VALUES(215, 23, 175);
INSERT INTO `products_options_values_to_products_options` VALUES(216, 24, 176);
INSERT INTO `products_options_values_to_products_options` VALUES(217, 24, 177);
INSERT INTO `products_options_values_to_products_options` VALUES(218, 24, 178);
INSERT INTO `products_options_values_to_products_options` VALUES(219, 24, 179);
INSERT INTO `products_options_values_to_products_options` VALUES(220, 24, 180);
INSERT INTO `products_options_values_to_products_options` VALUES(221, 24, 181);
INSERT INTO `products_options_values_to_products_options` VALUES(226, 26, 0);
INSERT INTO `products_options_values_to_products_options` VALUES(227, 27, 186);
INSERT INTO `products_options_values_to_products_options` VALUES(510, 24, 414);
INSERT INTO `products_options_values_to_products_options` VALUES(513, 24, 417);
INSERT INTO `products_options_values_to_products_options` VALUES(230, 27, 189);
INSERT INTO `products_options_values_to_products_options` VALUES(360, 36, 274);
INSERT INTO `products_options_values_to_products_options` VALUES(512, 24, 416);
INSERT INTO `products_options_values_to_products_options` VALUES(511, 24, 415);
INSERT INTO `products_options_values_to_products_options` VALUES(241, 31, 0);
INSERT INTO `products_options_values_to_products_options` VALUES(242, 30, 197);
INSERT INTO `products_options_values_to_products_options` VALUES(243, 30, 198);
INSERT INTO `products_options_values_to_products_options` VALUES(245, 32, 199);
INSERT INTO `products_options_values_to_products_options` VALUES(246, 32, 200);
INSERT INTO `products_options_values_to_products_options` VALUES(247, 32, 201);
INSERT INTO `products_options_values_to_products_options` VALUES(248, 32, 202);
INSERT INTO `products_options_values_to_products_options` VALUES(249, 32, 203);
INSERT INTO `products_options_values_to_products_options` VALUES(251, 32, 205);
INSERT INTO `products_options_values_to_products_options` VALUES(252, 32, 206);
INSERT INTO `products_options_values_to_products_options` VALUES(253, 32, 207);
INSERT INTO `products_options_values_to_products_options` VALUES(254, 32, 208);
INSERT INTO `products_options_values_to_products_options` VALUES(255, 32, 209);
INSERT INTO `products_options_values_to_products_options` VALUES(256, 32, 210);
INSERT INTO `products_options_values_to_products_options` VALUES(257, 32, 211);
INSERT INTO `products_options_values_to_products_options` VALUES(258, 33, 212);
INSERT INTO `products_options_values_to_products_options` VALUES(259, 33, 213);
INSERT INTO `products_options_values_to_products_options` VALUES(260, 33, 214);
INSERT INTO `products_options_values_to_products_options` VALUES(261, 33, 215);
INSERT INTO `products_options_values_to_products_options` VALUES(262, 33, 216);
INSERT INTO `products_options_values_to_products_options` VALUES(263, 33, 217);
INSERT INTO `products_options_values_to_products_options` VALUES(264, 33, 218);
INSERT INTO `products_options_values_to_products_options` VALUES(265, 33, 219);
INSERT INTO `products_options_values_to_products_options` VALUES(266, 33, 220);
INSERT INTO `products_options_values_to_products_options` VALUES(267, 33, 221);
INSERT INTO `products_options_values_to_products_options` VALUES(268, 34, 222);
INSERT INTO `products_options_values_to_products_options` VALUES(269, 34, 223);
INSERT INTO `products_options_values_to_products_options` VALUES(272, 35, 0);
INSERT INTO `products_options_values_to_products_options` VALUES(271, 34, 225);
INSERT INTO `products_options_values_to_products_options` VALUES(273, 36, 226);
INSERT INTO `products_options_values_to_products_options` VALUES(274, 36, 227);
INSERT INTO `products_options_values_to_products_options` VALUES(285, 38, 236);
INSERT INTO `products_options_values_to_products_options` VALUES(276, 36, 229);
INSERT INTO `products_options_values_to_products_options` VALUES(282, 37, 234);
INSERT INTO `products_options_values_to_products_options` VALUES(278, 36, 231);
INSERT INTO `products_options_values_to_products_options` VALUES(281, 37, 233);
INSERT INTO `products_options_values_to_products_options` VALUES(284, 37, 235);
INSERT INTO `products_options_values_to_products_options` VALUES(286, 38, 237);
INSERT INTO `products_options_values_to_products_options` VALUES(309, 54, 0);
INSERT INTO `products_options_values_to_products_options` VALUES(288, 40, 0);
INSERT INTO `products_options_values_to_products_options` VALUES(290, 41, 0);
INSERT INTO `products_options_values_to_products_options` VALUES(310, 55, 0);
INSERT INTO `products_options_values_to_products_options` VALUES(292, 43, 0);
INSERT INTO `products_options_values_to_products_options` VALUES(293, 44, 0);
INSERT INTO `products_options_values_to_products_options` VALUES(294, 45, 0);
INSERT INTO `products_options_values_to_products_options` VALUES(295, 46, 0);
INSERT INTO `products_options_values_to_products_options` VALUES(296, 48, 0);
INSERT INTO `products_options_values_to_products_options` VALUES(297, 49, 0);
INSERT INTO `products_options_values_to_products_options` VALUES(314, 59, 0);
INSERT INTO `products_options_values_to_products_options` VALUES(307, 52, 0);
INSERT INTO `products_options_values_to_products_options` VALUES(311, 56, 0);
INSERT INTO `products_options_values_to_products_options` VALUES(308, 53, 0);
INSERT INTO `products_options_values_to_products_options` VALUES(302, 51, 0);
INSERT INTO `products_options_values_to_products_options` VALUES(312, 57, 0);
INSERT INTO `products_options_values_to_products_options` VALUES(313, 58, 0);
INSERT INTO `products_options_values_to_products_options` VALUES(306, 47, 0);
INSERT INTO `products_options_values_to_products_options` VALUES(315, 60, 0);
INSERT INTO `products_options_values_to_products_options` VALUES(316, 61, 0);
INSERT INTO `products_options_values_to_products_options` VALUES(317, 62, 0);
INSERT INTO `products_options_values_to_products_options` VALUES(318, 63, 0);
INSERT INTO `products_options_values_to_products_options` VALUES(319, 64, 0);
INSERT INTO `products_options_values_to_products_options` VALUES(320, 65, 0);
INSERT INTO `products_options_values_to_products_options` VALUES(321, 66, 0);
INSERT INTO `products_options_values_to_products_options` VALUES(322, 67, 0);
INSERT INTO `products_options_values_to_products_options` VALUES(323, 68, 0);
INSERT INTO `products_options_values_to_products_options` VALUES(325, 24, 239);
INSERT INTO `products_options_values_to_products_options` VALUES(326, 24, 240);
INSERT INTO `products_options_values_to_products_options` VALUES(327, 24, 241);
INSERT INTO `products_options_values_to_products_options` VALUES(328, 24, 242);
INSERT INTO `products_options_values_to_products_options` VALUES(330, 24, 244);
INSERT INTO `products_options_values_to_products_options` VALUES(331, 24, 245);
INSERT INTO `products_options_values_to_products_options` VALUES(332, 24, 246);
INSERT INTO `products_options_values_to_products_options` VALUES(333, 24, 247);
INSERT INTO `products_options_values_to_products_options` VALUES(334, 24, 248);
INSERT INTO `products_options_values_to_products_options` VALUES(335, 24, 249);
INSERT INTO `products_options_values_to_products_options` VALUES(336, 24, 250);
INSERT INTO `products_options_values_to_products_options` VALUES(337, 24, 251);
INSERT INTO `products_options_values_to_products_options` VALUES(338, 24, 252);
INSERT INTO `products_options_values_to_products_options` VALUES(339, 24, 253);
INSERT INTO `products_options_values_to_products_options` VALUES(340, 24, 254);
INSERT INTO `products_options_values_to_products_options` VALUES(341, 24, 255);
INSERT INTO `products_options_values_to_products_options` VALUES(342, 24, 256);
INSERT INTO `products_options_values_to_products_options` VALUES(343, 24, 257);
INSERT INTO `products_options_values_to_products_options` VALUES(344, 24, 258);
INSERT INTO `products_options_values_to_products_options` VALUES(345, 24, 259);
INSERT INTO `products_options_values_to_products_options` VALUES(346, 24, 260);
INSERT INTO `products_options_values_to_products_options` VALUES(347, 24, 261);
INSERT INTO `products_options_values_to_products_options` VALUES(348, 24, 262);
INSERT INTO `products_options_values_to_products_options` VALUES(349, 24, 263);
INSERT INTO `products_options_values_to_products_options` VALUES(350, 24, 264);
INSERT INTO `products_options_values_to_products_options` VALUES(351, 24, 265);
INSERT INTO `products_options_values_to_products_options` VALUES(352, 24, 266);
INSERT INTO `products_options_values_to_products_options` VALUES(353, 24, 267);
INSERT INTO `products_options_values_to_products_options` VALUES(354, 24, 268);
INSERT INTO `products_options_values_to_products_options` VALUES(355, 24, 269);
INSERT INTO `products_options_values_to_products_options` VALUES(356, 24, 270);
INSERT INTO `products_options_values_to_products_options` VALUES(357, 24, 271);
INSERT INTO `products_options_values_to_products_options` VALUES(358, 23, 272);
INSERT INTO `products_options_values_to_products_options` VALUES(359, 24, 273);
INSERT INTO `products_options_values_to_products_options` VALUES(361, 33, 275);
INSERT INTO `products_options_values_to_products_options` VALUES(362, 33, 276);
INSERT INTO `products_options_values_to_products_options` VALUES(363, 18, 277);
INSERT INTO `products_options_values_to_products_options` VALUES(364, 18, 278);
INSERT INTO `products_options_values_to_products_options` VALUES(680, 1, 578);
INSERT INTO `products_options_values_to_products_options` VALUES(384, 16, 298);
INSERT INTO `products_options_values_to_products_options` VALUES(385, 32, 299);
INSERT INTO `products_options_values_to_products_options` VALUES(388, 1, 302);
INSERT INTO `products_options_values_to_products_options` VALUES(390, 27, 304);
INSERT INTO `products_options_values_to_products_options` VALUES(391, 24, 305);
INSERT INTO `products_options_values_to_products_options` VALUES(392, 24, 306);
INSERT INTO `products_options_values_to_products_options` VALUES(393, 24, 307);
INSERT INTO `products_options_values_to_products_options` VALUES(394, 24, 308);
INSERT INTO `products_options_values_to_products_options` VALUES(401, 24, 313);
INSERT INTO `products_options_values_to_products_options` VALUES(402, 34, 314);
INSERT INTO `products_options_values_to_products_options` VALUES(403, 34, 315);
INSERT INTO `products_options_values_to_products_options` VALUES(400, 24, 312);
INSERT INTO `products_options_values_to_products_options` VALUES(404, 34, 316);
INSERT INTO `products_options_values_to_products_options` VALUES(413, 24, 325);
INSERT INTO `products_options_values_to_products_options` VALUES(414, 24, 326);
INSERT INTO `products_options_values_to_products_options` VALUES(415, 24, 327);
INSERT INTO `products_options_values_to_products_options` VALUES(416, 24, 328);
INSERT INTO `products_options_values_to_products_options` VALUES(417, 24, 329);
INSERT INTO `products_options_values_to_products_options` VALUES(418, 24, 330);
INSERT INTO `products_options_values_to_products_options` VALUES(419, 24, 331);
INSERT INTO `products_options_values_to_products_options` VALUES(420, 24, 332);
INSERT INTO `products_options_values_to_products_options` VALUES(421, 24, 333);
INSERT INTO `products_options_values_to_products_options` VALUES(422, 24, 334);
INSERT INTO `products_options_values_to_products_options` VALUES(423, 24, 335);
INSERT INTO `products_options_values_to_products_options` VALUES(424, 24, 336);
INSERT INTO `products_options_values_to_products_options` VALUES(427, 23, 339);
INSERT INTO `products_options_values_to_products_options` VALUES(428, 23, 340);
INSERT INTO `products_options_values_to_products_options` VALUES(445, 1, 355);
INSERT INTO `products_options_values_to_products_options` VALUES(447, 32, 357);
INSERT INTO `products_options_values_to_products_options` VALUES(446, 16, 356);
INSERT INTO `products_options_values_to_products_options` VALUES(437, 1, 347);
INSERT INTO `products_options_values_to_products_options` VALUES(438, 16, 348);
INSERT INTO `products_options_values_to_products_options` VALUES(439, 32, 349);
INSERT INTO `products_options_values_to_products_options` VALUES(509, 24, 413);
INSERT INTO `products_options_values_to_products_options` VALUES(452, 1, 361);
INSERT INTO `products_options_values_to_products_options` VALUES(453, 16, 362);
INSERT INTO `products_options_values_to_products_options` VALUES(454, 32, 363);
INSERT INTO `products_options_values_to_products_options` VALUES(458, 1, 367);
INSERT INTO `products_options_values_to_products_options` VALUES(459, 16, 368);
INSERT INTO `products_options_values_to_products_options` VALUES(460, 32, 369);
INSERT INTO `products_options_values_to_products_options` VALUES(464, 1, 373);
INSERT INTO `products_options_values_to_products_options` VALUES(465, 16, 374);
INSERT INTO `products_options_values_to_products_options` VALUES(466, 32, 375);
INSERT INTO `products_options_values_to_products_options` VALUES(470, 34, 379);
INSERT INTO `products_options_values_to_products_options` VALUES(485, 1, 391);
INSERT INTO `products_options_values_to_products_options` VALUES(494, 24, 400);
INSERT INTO `products_options_values_to_products_options` VALUES(543, 24, 447);
INSERT INTO `products_options_values_to_products_options` VALUES(495, 24, 401);
INSERT INTO `products_options_values_to_products_options` VALUES(496, 24, 402);
INSERT INTO `products_options_values_to_products_options` VALUES(542, 23, 446);
INSERT INTO `products_options_values_to_products_options` VALUES(514, 24, 418);
INSERT INTO `products_options_values_to_products_options` VALUES(515, 24, 419);
INSERT INTO `products_options_values_to_products_options` VALUES(516, 24, 420);
INSERT INTO `products_options_values_to_products_options` VALUES(517, 24, 421);
INSERT INTO `products_options_values_to_products_options` VALUES(559, 38, 457);
INSERT INTO `products_options_values_to_products_options` VALUES(526, 36, 430);
INSERT INTO `products_options_values_to_products_options` VALUES(527, 36, 431);
INSERT INTO `products_options_values_to_products_options` VALUES(539, 24, 443);
INSERT INTO `products_options_values_to_products_options` VALUES(538, 24, 442);
INSERT INTO `products_options_values_to_products_options` VALUES(537, 36, 441);
INSERT INTO `products_options_values_to_products_options` VALUES(531, 36, 435);
INSERT INTO `products_options_values_to_products_options` VALUES(532, 36, 436);
INSERT INTO `products_options_values_to_products_options` VALUES(533, 36, 437);
INSERT INTO `products_options_values_to_products_options` VALUES(534, 36, 438);
INSERT INTO `products_options_values_to_products_options` VALUES(535, 36, 439);
INSERT INTO `products_options_values_to_products_options` VALUES(536, 36, 440);
INSERT INTO `products_options_values_to_products_options` VALUES(540, 24, 444);
INSERT INTO `products_options_values_to_products_options` VALUES(541, 24, 445);
INSERT INTO `products_options_values_to_products_options` VALUES(560, 38, 458);
INSERT INTO `products_options_values_to_products_options` VALUES(561, 24, 459);
INSERT INTO `products_options_values_to_products_options` VALUES(566, 1, 464);
INSERT INTO `products_options_values_to_products_options` VALUES(685, 27, 583);
INSERT INTO `products_options_values_to_products_options` VALUES(568, 32, 466);
INSERT INTO `products_options_values_to_products_options` VALUES(600, 24, 498);
INSERT INTO `products_options_values_to_products_options` VALUES(598, 36, 496);
INSERT INTO `products_options_values_to_products_options` VALUES(601, 24, 499);
INSERT INTO `products_options_values_to_products_options` VALUES(602, 16, 500);
INSERT INTO `products_options_values_to_products_options` VALUES(603, 16, 501);
INSERT INTO `products_options_values_to_products_options` VALUES(604, 32, 502);
INSERT INTO `products_options_values_to_products_options` VALUES(605, 32, 503);
INSERT INTO `products_options_values_to_products_options` VALUES(606, 1, 504);
INSERT INTO `products_options_values_to_products_options` VALUES(619, 16, 517);
INSERT INTO `products_options_values_to_products_options` VALUES(612, 1, 510);
INSERT INTO `products_options_values_to_products_options` VALUES(620, 32, 518);
INSERT INTO `products_options_values_to_products_options` VALUES(618, 1, 516);
INSERT INTO `products_options_values_to_products_options` VALUES(635, 23, 533);
INSERT INTO `products_options_values_to_products_options` VALUES(624, 1, 522);
INSERT INTO `products_options_values_to_products_options` VALUES(625, 16, 523);
INSERT INTO `products_options_values_to_products_options` VALUES(626, 32, 524);
INSERT INTO `products_options_values_to_products_options` VALUES(630, 86, 528);
INSERT INTO `products_options_values_to_products_options` VALUES(632, 86, 530);
INSERT INTO `products_options_values_to_products_options` VALUES(649, 24, 547);
INSERT INTO `products_options_values_to_products_options` VALUES(650, 24, 548);
INSERT INTO `products_options_values_to_products_options` VALUES(651, 24, 549);
INSERT INTO `products_options_values_to_products_options` VALUES(652, 24, 550);
INSERT INTO `products_options_values_to_products_options` VALUES(653, 24, 551);
INSERT INTO `products_options_values_to_products_options` VALUES(658, 24, 556);
INSERT INTO `products_options_values_to_products_options` VALUES(663, 24, 561);
INSERT INTO `products_options_values_to_products_options` VALUES(664, 24, 562);
INSERT INTO `products_options_values_to_products_options` VALUES(665, 23, 563);
INSERT INTO `products_options_values_to_products_options` VALUES(684, 17, 582);
INSERT INTO `products_options_values_to_products_options` VALUES(682, 32, 580);
INSERT INTO `products_options_values_to_products_options` VALUES(681, 16, 579);
INSERT INTO `products_options_values_to_products_options` VALUES(674, 1, 572);
INSERT INTO `products_options_values_to_products_options` VALUES(675, 16, 573);
INSERT INTO `products_options_values_to_products_options` VALUES(676, 32, 574);
INSERT INTO `products_options_values_to_products_options` VALUES(678, 17, 576);
INSERT INTO `products_options_values_to_products_options` VALUES(679, 27, 577);
INSERT INTO `products_options_values_to_products_options` VALUES(686, 1, 584);
INSERT INTO `products_options_values_to_products_options` VALUES(687, 16, 585);
INSERT INTO `products_options_values_to_products_options` VALUES(688, 32, 586);
INSERT INTO `products_options_values_to_products_options` VALUES(690, 17, 588);
INSERT INTO `products_options_values_to_products_options` VALUES(691, 27, 589);
INSERT INTO `products_options_values_to_products_options` VALUES(692, 23, 590);
INSERT INTO `products_options_values_to_products_options` VALUES(694, 16, 592);
INSERT INTO `products_options_values_to_products_options` VALUES(696, 1, 593);
INSERT INTO `products_options_values_to_products_options` VALUES(697, 16, 594);
INSERT INTO `products_options_values_to_products_options` VALUES(698, 32, 595);
INSERT INTO `products_options_values_to_products_options` VALUES(700, 17, 597);
INSERT INTO `products_options_values_to_products_options` VALUES(701, 27, 598);
INSERT INTO `products_options_values_to_products_options` VALUES(719, 24, 615);
INSERT INTO `products_options_values_to_products_options` VALUES(720, 24, 616);
INSERT INTO `products_options_values_to_products_options` VALUES(722, 24, 618);
INSERT INTO `products_options_values_to_products_options` VALUES(723, 24, 619);
INSERT INTO `products_options_values_to_products_options` VALUES(724, 24, 620);
INSERT INTO `products_options_values_to_products_options` VALUES(726, 24, 621);
INSERT INTO `products_options_values_to_products_options` VALUES(754, 1, 648);
INSERT INTO `products_options_values_to_products_options` VALUES(755, 16, 649);
INSERT INTO `products_options_values_to_products_options` VALUES(756, 32, 650);
INSERT INTO `products_options_values_to_products_options` VALUES(758, 17, 652);
INSERT INTO `products_options_values_to_products_options` VALUES(759, 27, 653);
INSERT INTO `products_options_values_to_products_options` VALUES(761, 23, 655);
INSERT INTO `products_options_values_to_products_options` VALUES(762, 23, 656);
INSERT INTO `products_options_values_to_products_options` VALUES(763, 23, 657);
